### ISSUE TITLE
Clean the 'Part' concept

### ISSUE THREAD

**Issue by Villemos** [Villemos/hbird-business#10]
Currently only the ground station is defined as an object model, where each part is defined as having one parent.

This concept should be extended to also cover the Components, i.e. archive, commanding chain, etc. 

The Parts should have a function 'getQualifiedName' which returns the complete path name. This is the name that should be used when setting 'issuedBy'. And the parameters emitted by a Part should always have the name [qualifiedPath]/[parameter name]

**Comment by laurikimmel** [comment]
See #46 - ID and Name convention
