### ISSUE TITLE
Change the way that objects are ID'ed and linked

### ISSUE THREAD

**Issue by Villemos** [Villemos/hbird-business#12]
The current way of relating Named objects takes two approaches;
1. The qualified name. The link is defines using the qualified name.
2. The NamedInstanceIdentfiier. The link is defines using the name, type, timestamp combination (instance)

Besides that two approaches is at least one too many, there are a number of specific issues to each approach;

In approach 1, if the structure of the assembly changes (not the parts or their names, but their logical location in the assembly), then the qualified name changes.The qualified name is thus not a unique ID globally for the mission, but for the mission IN THE CURRENT ASSEMBLY. This is ok for assemblies that dont change, but is in flexible. 

In approach 2 the Name and not the Qualified Name is used.

The new approach could consider to use the Named::ID attribute, which is a unique UUID generated for each object.

**Comment by laurikimmel** [comment]
See #46 - ID and Name convention
