### ISSUE TITLE
Improve IPart & Part 

### ISSUE THREAD

**Issue by laurikimmel** [Villemos/hbird-business#19]
`Part` class has two methods with almost the same logic - `setParent` and `setIsPartOf`. Remove one of them.

Store parents absolute name in `IPart` / `Part` instead of parent object. This will reduce amount of data at serialization and deserialization. 

Add new method `resolveParent` to retreive the `IPart` parent object on demand.

See #18 - Add getByAbsoluteName method to ICatalogue

**Comment by Villemos** [comment]
1. Removed parent attribute completly.
2. ID of parent stored in attribute isPartOf
3. resolveParent added to IPartManagement API
