### ISSUE TITLE
Clarify the usage of name, type, class

### ISSUE THREAD

**Issue by Villemos** [Villemos/hbird-business#9]
The Named attributes 
- Name.
- Type.
- Class

Are not used consistently. Update the code so that
- Name is used to name an object and can be any value.
- Type is a limited subset of types such as 'Command', 'Monitoring' and 'Event'. These should be represented with appropiate interfaces.
- Class is the simple name of the Java class.

**Comment by laurikimmel** [comment]
> Name is used to name an object and can be any value.

Still keep in mind the agreed hierarchical naming convention.

Examples:
- Satellite/X-Cube
- GroundStation/ABC
- WeatherStation/ABC
- Host/192.168.10.10
- Satellite/X-Cube/COM/power
- GroundStation/ABC/rotator1/elevation
- WeatherStation/ABC/windSpeed
- Host/192.168.10.10/loadAverage
- etc.

**Comment by laurikimmel** [comment]
See #46 - ID and Name convention
